// setup calls
export const INIT_APP = 'INIT_APP';

// Web3 lookups
export const GET_CURRENT_NETWORK = 'GET_CURRENT_NETWORK';

// Contract lookup calls
export const GET_ALL_ASSETS = 'GET_ALL_ASSETS';
export const NEXT_HASH = 'NEXT_HASH';
export const GET_ASSETS_PURCHASED_FOR_ACCOUNT = 'GET_ASSETS_PURCHASED_FOR_ACCOUNT';
export const REFRESH_CONTRACT_DETAILS = 'REFRESH_CONTRACT_DETAILS';

// TOKN specific
export const TOKN_REFRESH_ACCOUNT_TOKENS_DETAILS = 'TOKN_REFRESH_ACCOUNT_TOKENS_DETAILS';
export const TOKN_UPDATE_NICKNAME = 'TOKN_UPDATE_NICKNAME';

// SAC specific
export const GET_SAC_DETAILS = 'GET_SAC_DETAILS';
export const SAC_UPDATE_ONLY_PURCHASED = 'SAC_UPDATE_ONLY_PURCHASED';
export const SAC_UPDATE_MAX_BLOCKS_PURCHASE = 'SAC_UPDATE_MAX_BLOCKS_PURCHASE';
export const SAC_UPDATE_MAX_PRICE_PRE_BLOCK = 'SAC_UPDATE_MAX_PRICE_PRE_BLOCK';


// minting
export const MINT = 'MINT';

