// setup calls
export const INIT_APP = 'INIT_APP';

// Web3 lookups
export const GET_CURRENT_NETWORK = 'GET_CURRENT_NETWORK';

// Contract lookup calls
export const GET_ALL_ASSETS = 'GET_ALL_ASSETS';
export const GET_ASSETS_PURCHASED_FOR_ACCOUNT = 'GET_ASSETS_PURCHASED_FOR_ACCOUNT';
export const REFRESH_CONTRACT_DETAILS = 'REFRESH_CONTRACT_DETAILS';

// Contract payment calls
export const PURCHASE_ASSET = 'PURCHASE_ASSET';
export const PURCHASE_ASSET_WITH_FIAT = 'PURCHASE_ASSET_WITH_FIAT';
export const REVERSE_PURCHASE_ASSET_WITH_FIAT = 'REVERSE_PURCHASE_ASSET_WITH_FIAT';

// Internal state triggers
export const RESET_PURCHASE_STATE = 'RESET_PURCHASE_STATE';

export const VERIFY_PURCHASE = 'VERIFY_PURCHASE';
